### ISSUE TITLE
Add explanation and benefits to README

### ISSUE THREAD

**Issue by cordovapolymer** [Polymer/lazy-imports#11]
how is this better than importHref?
like `this.importHref('element.htm',  null, null, true);`

**Comment by JosefJezek** [comment]
https://youtu.be/guYHn0P8bKQ?t=10m45s

**Comment by stramel** [comment]
Would there be benefit to adding some documentation that summarizes what @justinfagnani said in that video? If not, this could probably be closed.

**Comment by justinfagnani** [comment]
I'll update the docs here.

Also, we're making progress on lazy-import support in the bundler: https://github.com/Polymer/polymer-bundler/pull/487

**Comment by stramel** [comment]
@rictic can we close this now with your updates to the readme?

**Comment by rictic** [comment]
Yep! This should be fixed by #31
