### ISSUE TITLE
Polymer.LazyImportsBehavior instead of LazyImportsBehavior in example

### ISSUE THREAD

**Issue by cordovapolymer** [Polymer/lazy-imports#15]
Polymer.LazyImportsBehavior instead of LazyImportsBehavior in example.

**Comment by stramel** [comment]
Please be sure to check that issues don't exist before creating them. Issue #4 and fixing PR #7

**Comment by stramel** [comment]
@garlicnation mind closing this one while you are at it? Thanks for addressing some things that have been outstanding!
