### ISSUE TITLE
support of lazy-imports in polymer-bundler

### ISSUE THREAD

**Issue by cordovapolymer** [Polymer/lazy-imports#17]
Currently imports inside `<link rel="lazy-import" href="lazy-element.html" group="lazy"> ` are not bundled into the build, so lazy-imports are incompatible with polymer-bundler.
I've created an issue in https://github.com/Polymer/polymer-bundler/issues/447

**Comment by stramel** [comment]
@justinfagnani Can you close this please as it is resolved with Polymer/polymer-bundler#487. Thanks!
