### ISSUE TITLE
Analyzer error with some elements when building

### ISSUE THREAD

**Issue by tpluscode** [Polymer/lazy-imports#23]
I'm trying to `polymer build` an app which uses `lazy-imports`. Some imports cause the build process to fail with message similar to

```
error: [cli.build.analyzer]   In src/my-app/my-app.html: [could-not-load] - Unable to load import:
```

where the `my-app` element is the container and not the culprit itself. Such as in the following snippet

``` html
<dom-module id="my-app">
  <link rel="lazy-import" group="lazy" href="my-elem.html">
  <template />
</dom-module>
```

When I try to `polymer analyze` either I don't get any errors. 

You can have a look ta [this repo+branch](https://github.com/PGS-dev/framapp-polymer/tree/lazy-imports) for an example (sorry not a minimal reproduction ATM). When you uncomment any of the three `lazy-import` in `framapp-polymer-app` element it's no longer possible to `polymer build` the project.

**Comment by stramel** [comment]
I noticed this as well when submitting a PR to PSK. The tooling still needs fleshed out for it. This appears to be related to the analyzer. 

Outstanding ones that need work:
~~[Polymer/polymer-analyzer#360](https://github.com/Polymer/polymer-analyzer/pull/360)~~
~~[Polymer/polymer-analyzer#543](https://github.com/Polymer/polymer-analyzer/pull/543)~~
~~[Polymer/polymer-analyzer#643](https://github.com/Polymer/polymer-analyzer/issues/643)~~
~~[Polymer/polymer-bundler#391](https://github.com/Polymer/polymer-bundler/pull/391)~~
~~[Polymer/polymer-bundler#447](https://github.com/Polymer/polymer-bundler/issues/447)~~
~~[Polymer/polymer-bundler#487](https://github.com/Polymer/polymer-bundler/pull/487)~~
~~[Polymer/polymer-bundler#494](https://github.com/Polymer/polymer-bundler/issues/494)~~
~~[Polymer/polymer-cli#139](https://github.com/Polymer/polymer-cli/issues/139)~~

**Comment by stramel** [comment]
@tpluscode @garlicnation @justinfagnani Can one of you close this? 

All issues except the cli issue which I'm not sure is still necessary. Tested some lazy-imports in a couple places and everything seems to be functioning correctly now.

**Comment by tpluscode** [comment]
Should I no longer have this problem with latest polymer-cli?

**Comment by stramel** [comment]
@tpluscode You shouldn't have any issues after this ~~https://github.com/Polymer/polymer-cli/pull/724~~ is merged and tagged.

**Comment by stramel** [comment]
There was another issue found with resolving the lazy-imports inside bundles. 
~~https://github.com/Polymer/polymer-bundler/issues/504~~

Linter is throwing Errors on lazy imports
~~https://github.com/Polymer/polymer-linter/issues/84~~

**Comment by stramel** [comment]
@tpluscode I believe all the tooling has been updated minus the linter. It would probably be good to close this out as, this was primarily around the build process. Will continue to track the linter issues over there.

**Comment by stramel** [comment]
@tpluscode Do you mine closing this? All outstanding issues have been completed.

**Comment by tpluscode** [comment]
Sure. Apparently my issues were fixed :balloon:. Happy to close.
