### ISSUE TITLE
Add License to Bower.json

### ISSUE THREAD

**Issue by AlbertoFdzM** [Polymer/lazy-imports#24]
In order to submit this package to [webcomponents.org](https://www.webcomponents.org/) the `bower.json` file must define a  license:

> The GitHub repository must be licensed under an Open Source Inititative (OSI) approved license. Please include a valid license or alternatively include an OSI approved license as an SPDX identifier (eg. "Apache-2.0") in the license field in the bower.json.

**Comment by stramel** [comment]
Added this to #21 based on `paper-input`

**Comment by stramel** [comment]
Moved to #25 due to conflicts from merging the 2.0-preview
