### ISSUE TITLE
Not working with Polymer Webpack Loader ...

### ISSUE THREAD

**Issue by ruud** [Polymer/lazy-imports#46]
We would like to use https://github.com/webpack-contrib/polymer-webpack-loader with the lazy-import together in our large application. Do you have a suggestion on how these could work together?

**Comment by stramel** [comment]
@ruud Disclaimer, I haven't used Webpack or the Polymer Webpack Loader.

I don't believe you need lazy-imports for handling dynamic imports. You should be able to just use Webpack's dynamic import instead. Like so, https://github.com/Banno/polymer-2-starter-kit-webpack/blob/master/src/my-app.html#L127-L138

Maybe @chadkillingsworth or @robdodson can help answer this?

Link found on Rob's post http://robdodson.me/how-to-use-polymer-with-webpack/ under code splitting

**Comment by ChadKillingsworth** [comment]
The loader can't handle Polymer style lazy-imports. The HTML and JS are not guaranteed to be in the same file and loaders can only look at a single file at a time.

Instead, you definitely want to use the native code splitting and lazy loading of the platform and webpack:

```js
Promise.all([
  import('./path/to/component1.html'),
  import('./path/to/component2.html')
]).then(() => {
  // components are loaded
});
```

**Comment by stramel** [comment]
I believe that this will be the direction of P3 as well. Utilizing ES Modules with Dynamic Imports.

Thanks for weighing in Chad!

**Comment by ruud** [comment]
Thanks for the reply!

Lazy imports plays an important part in our application development. So we would like to continue using it. But we also would like to use webpack as our build tool. Keeping our code independent of webpack, we need some extraction. I just created a loader myself to do just that. It recasts the ```importLazyGroup```  to ```Promise.all```, like @ChadKillingsworth suggested.

**Comment by stramel** [comment]
@ruud Do you mind closing this?

**Comment by ruud** [comment]
Our loader, which recasts the lazy group into import()s is working for us. Best of both worlds :)

**Comment by tylergraf** [comment]
@ruud I was going to write my own loader because we use `lazy-imports` heavily as well. Would you mind sharing your loader? Even in a gist if you don't want to maintain it.

**Comment by ruud** [comment]
Hi, of course. I will share a gist

**Comment by ruud** [comment]
@tylergraf , hereby the link https://gist.github.com/ruud/056d21849bebde00d867cce112f7dad3
